# Generated by Django 5.1.1 on 2024-10-30 01:44

import django.db.models.deletion
import django_resized.forms
import medicos.models
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("usuarios", "0002_alter_usuario_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Especialidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "especialidad",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Especialidad"
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "update_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Fecha de Actualización",
                    ),
                ),
                (
                    "genero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.genero",
                        verbose_name="Genero",
                    ),
                ),
            ],
            options={
                "verbose_name": "Especialidad",
                "verbose_name_plural": "Especialidades",
            },
        ),
        migrations.CreateModel(
            name="Medico",
            fields=[
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Primer Nombre"),
                ),
                (
                    "apellido",
                    models.CharField(max_length=100, verbose_name="Primer Apellido"),
                ),
                (
                    "telefono",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Número de Teléfono"
                    ),
                ),
                (
                    "institucion",
                    models.CharField(max_length=100, verbose_name="Institución"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foto",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=["middle", "center"],
                        db_column="medic_image",
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=-1,
                        scale=None,
                        size=[736, 736],
                        upload_to=medicos.models.generar_nombre,
                        verbose_name="Foto de Medico",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "update_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "agregado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Agregado Por",
                    ),
                ),
                (
                    "especialidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicos.especialidad",
                        verbose_name="Especialidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medico",
                "verbose_name_plural": "Medicos",
            },
        ),
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("diagnostico", models.TextField(verbose_name="Diagnostico")),
                ("tratamiento", models.TextField(verbose_name="Tratamiento")),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "update_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicos.medico",
                        verbose_name="Medico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consulta",
                "verbose_name_plural": "Consultas",
            },
        ),
    ]
