# Generated by Django 5.1.1 on 2024-10-30 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicos", "0001_initial"),
        ("usuarios", "0004_alter_usuario_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="especialidad",
            name="genero",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="usuarios.genero",
                verbose_name="Genero",
            ),
        ),
    ]
