services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - minio
      - db
    env_file:
      - .env.local
    volumes:
      - ./:/app
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ./data:/data
    command: server --console-address ":9001" /data
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/backend/
    volumes:
      - ./data:/var/lib/postgresql/data