# Generated by Django 5.1.1 on 2024-10-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(
                blank=True,
                default="no-email.f8488c39014e4ba8bae7c80224cb91c6@noemail.com",
                max_length=254,
                null=True,
                unique=True,
                verbose_name="Correo Electrónico",
            ),
        ),
    ]
