# Generated by Django 5.1.1 on 2024-10-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0003_alter_usuario_email_alter_usuario_genero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(
                blank=True,
                default="no-email.0084727e58254145abec4b15ddc4a4a9@noemail.com",
                max_length=254,
                null=True,
                unique=True,
                verbose_name="Correo Electrónico",
            ),
        ),
    ]
