# Generated by Django 5.1.1 on 2024-11-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0005_rename_emergency_contact_usuario_telefono_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(
                blank=True,
                default="no-email.4543e9d620a94b1789207daa155df53c@noemail.com",
                max_length=254,
                null=True,
                unique=True,
                verbose_name="Correo Electrónico",
            ),
        ),
    ]
