# Generated by Django 5.1.1 on 2024-11-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0006_alter_usuario_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(
                blank=True,
                default="no-email.23cabc894352487cafbdf9104ee9cd72@noemail.com",
                max_length=254,
                null=True,
                unique=True,
                verbose_name="Correo Electrónico",
            ),
        ),
    ]
